// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJVye3tyI5-E7PlO2fSZ-jwa89lRfSrA',
    appId: '1:1023837237655:web:a9b0c09fe203bf6648d4d2',
    messagingSenderId: '1023837237655',
    projectId: 'hungry-app-4760d',
    authDomain: 'hungry-app-4760d.firebaseapp.com',
    storageBucket: 'hungry-app-4760d.firebasestorage.app',
    measurementId: 'G-NK2SNEMRPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgwipHClpI9D9MLhAdvRw39mXtoJpv__Q',
    appId: '1:1023837237655:android:225eebdff3799ae948d4d2',
    messagingSenderId: '1023837237655',
    projectId: 'hungry-app-4760d',
    storageBucket: 'hungry-app-4760d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC9-qqnUhmcT9lQ16tQyBrDPqj1tYV4BM',
    appId: '1:1023837237655:ios:3d47ac61605f22b948d4d2',
    messagingSenderId: '1023837237655',
    projectId: 'hungry-app-4760d',
    storageBucket: 'hungry-app-4760d.firebasestorage.app',
    iosBundleId: 'com.example.hungryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC9-qqnUhmcT9lQ16tQyBrDPqj1tYV4BM',
    appId: '1:1023837237655:ios:3d47ac61605f22b948d4d2',
    messagingSenderId: '1023837237655',
    projectId: 'hungry-app-4760d',
    storageBucket: 'hungry-app-4760d.firebasestorage.app',
    iosBundleId: 'com.example.hungryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJVye3tyI5-E7PlO2fSZ-jwa89lRfSrA',
    appId: '1:1023837237655:web:940437e4936177ab48d4d2',
    messagingSenderId: '1023837237655',
    projectId: 'hungry-app-4760d',
    authDomain: 'hungry-app-4760d.firebaseapp.com',
    storageBucket: 'hungry-app-4760d.firebasestorage.app',
    measurementId: 'G-98JC3327PM',
  );
}
