// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:hungry_app/features/cart_feature/data/models/cart_item_model.dart';
import 'package:hungry_app/features/favourite_feature/data/models/favorite_model.dart';
import 'package:hungry_app/features/home_feature/data/models/product_model.dart';
import 'package:hungry_app/features/product_details_feature/data/models/side_options_model.dart';
import 'package:hungry_app/features/product_details_feature/data/models/toppings_model.dart';

import 'features/checkout_and_order_history_feature/data/models/order_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(FavouriteModelAdapter());
    registerAdapter(OrderModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(SideOptionsModelAdapter());
    registerAdapter(ToppingModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(FavouriteModelAdapter());
    registerAdapter(OrderModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(SideOptionsModelAdapter());
    registerAdapter(ToppingModelAdapter());
  }
}
